import {
  Apple,
  Bike,
  BookOpen,
  Brain,
  Brush,
  Cigarette,
  Coffee,
  Dumbbell,
  Flower,
  Footprints,
  GlassWater,
  GraduationCap,
  Guitar,
  Heart,
  Languages,
  Leaf,
  type LucideIcon,
  Moon,
  Music,
  NotebookPen,
  PersonStanding,
  Pill,
  Smartphone,
  Sun,
  Utensils,
  Wallet,
  Wine,
} from 'lucide-react';

/**
 * Iconos disponibles para los hábitos, identificados por su nombre en Lucide.
 * Se importan uno a uno para no incluir la librería entera en el bundle.
 */
export const HABIT_ICONS: Readonly<Record<string, { icon: LucideIcon; label: string }>> = {
  'glass-water': { icon: GlassWater, label: 'Vaso de agua' },
  'book-open': { icon: BookOpen, label: 'Libro' },
  dumbbell: { icon: Dumbbell, label: 'Pesas' },
  flower: { icon: Flower, label: 'Flor' },
  moon: { icon: Moon, label: 'Luna' },
  sun: { icon: Sun, label: 'Sol' },
  footprints: { icon: Footprints, label: 'Pasos' },
  'notebook-pen': { icon: NotebookPen, label: 'Cuaderno' },
  'person-standing': { icon: PersonStanding, label: 'Persona' },
  bike: { icon: Bike, label: 'Bicicleta' },
  apple: { icon: Apple, label: 'Manzana' },
  utensils: { icon: Utensils, label: 'Cubiertos' },
  pill: { icon: Pill, label: 'Pastilla' },
  heart: { icon: Heart, label: 'Corazón' },
  brain: { icon: Brain, label: 'Cerebro' },
  leaf: { icon: Leaf, label: 'Hoja' },
  music: { icon: Music, label: 'Música' },
  guitar: { icon: Guitar, label: 'Guitarra' },
  brush: { icon: Brush, label: 'Pincel' },
  languages: { icon: Languages, label: 'Idiomas' },
  'graduation-cap': { icon: GraduationCap, label: 'Estudio' },
  wallet: { icon: Wallet, label: 'Cartera' },
  smartphone: { icon: Smartphone, label: 'Móvil' },
  coffee: { icon: Coffee, label: 'Café' },
  wine: { icon: Wine, label: 'Copa' },
  cigarette: { icon: Cigarette, label: 'Cigarrillo' },
};

export const HABIT_ICON_NAMES = Object.keys(HABIT_ICONS);
